#!/bin/bash

OUTPUT_FILE="output.pdf"
PDFUNITE="/usr/bin/pdfunite"

message() {
    /usr/bin/notify-send "$@"
}

if [[ -e "$OUTPUT_FILE" ]]; then
  message "File already exists: $OUTPUT_FILE"
  exit 1
fi

$PDFUNITE $NAUTILUS_SCRIPT_SELECTED_FILE_PATHS $OUTPUT_FILE
[[ $? -eq 0 ]] || message "pdfunite failed"
