#!/bin/bash

# This script merges all selected PDF files into a single PDF file.
# The output is written to "output.pdf" in the current working directory.
# If the output file already exists, the script aborts to prevent overwriting.

OUTPUT_FILE="output.pdf"
PDFUNITE="/usr/bin/pdfunite"

message() {
    /usr/bin/notify-send "$@"
}

if [[ -e "$OUTPUT_FILE" ]]; then
  message "File already exists: $OUTPUT_FILE"
  exit 1
fi

$PDFUNITE $NAUTILUS_SCRIPT_SELECTED_FILE_PATHS $OUTPUT_FILE
[[ $? -eq 0 ]] || message "pdfunite failed"
