#!/bin/bash

OUTPUT_FILE=output.pdf

message()
{
    /usr/bin/notify-send "$@"
}

if [ -e $OUTPUT_FILE ]; then
  message "Output file already exists $OUTPUT_FILE"
  exit 1
fi

/usr/bin/pdfunite $NAUTILUS_SCRIPT_SELECTED_FILE_PATHS $OUTPUT_FILE
[[ $? -eq 0 ]] || message "pdfunite failed"
