#!/bin/bash

ORG_DIR="org_rotate"
CONVERT="/usr/bin/convert"

if [[ -z "${ROTATE_ANGLE}" ]]; then 
    ROTATE_ANGLE=-90
fi

fail() {
    /usr/bin/notify-send "$@"
    exit 1
}

rotateFiles()
{
    ROTATE_ANGLE=$1

    # Check if we can make backup
    for FPATH in $NAUTILUS_SCRIPT_SELECTED_FILE_PATHS; do
        FILE=${FPATH##*/}
        if [[ -e "$ORG_DIR"/"$FILE" ]]; then
            fail "File exists: $ORG_DIR/$FILE"
        fi
    done

    # Make backup and convert. Abort in case of error
    for FPATH in $NAUTILUS_SCRIPT_SELECTED_FILE_PATHS; do
        FILE=${FPATH##*/}

        /usr/bin/mv ${FILE} ${ORG_DIR}/${FILE}
        [[ $? -eq 0 ]] || fail "Failed moving file: ${FILE} to ${ORG_DIR}/${FILE}"

        /usr/bin/convert -rotate $ROTATE_ANGLE ${ORG_DIR}/${FILE} ${FILE}
        [[ $? -eq 0 ]] || fail "Failed converting file: ${FILE}"
    done
}

mkdir $ORG_DIR

rotateFiles ${ROTATE_ANGLE}
