#!/bin/bash

PDFTK="/snap/bin/pdftk"

if [[ -z "${ROTATE_COMMAND}" ]]; then 
    ROTATE_COMMAND=1-enddown
fi

fail() {
    /usr/bin/notify-send "$@"
    exit 1
}

rotatePdf() {
    ROTATE_COMMAND=$1

    # Check for output files conflicts
    for FPATH in $NAUTILUS_SCRIPT_SELECTED_FILE_PATHS; do
        FILE=${FPATH##*/}
        NEW_FILE=`echo "${FILE}" | cut -d'.' -f1`_R.pdf
        if [[ -e "$NEW_FILE" ]]; then
            fail "File exists: $NEW_FILE"
        fi
    done

    # Rotate
    for FPATH in $NAUTILUS_SCRIPT_SELECTED_FILE_PATHS; do
        FILE=${FPATH##*/}
        NEW_FILE=`echo "${FILE}" | cut -d'.' -f1`_R.pdf
        if ! $PDFTK ${FILE} cat $ROTATE_COMMAND output $NEW_FILE; then
            fail "Failed totating: $FILE"
        fi
    done
}

mkdir $DEST_DIR
rotatePdf $ROTATE_COMMAND
