#!/bin/bash

ORG_DIR=org
LOG=$ORG_DIR/log.txt

if [ -z "${ROTATE_ANGLE}" ]; then 
    ROTATE_ANGLE=-90
fi

fail()
{
    echo "$@" >> $LOG
    /usr/bin/notify-send "$@"
    exit 1
}

rotateFiles()
{
    ROTATE_ANGLE=$1
    echo $ROTATE_ANGLE > $LOG
    echo "Files:"$NAUTILUS_SCRIPT_SELECTED_FILE_PATHS >> $LOG

    # Check if we can make backup
    for FPATH in $NAUTILUS_SCRIPT_SELECTED_FILE_PATHS
    do
        FILE=${FPATH##*/}
        if [ -e $ORG_DIR/$FILE ]; then
            fail "File already exists $ORG_DIR/$FILE"
        fi
    done

    # Make backup and convert. Abort in case of error
    for FPATH in $NAUTILUS_SCRIPT_SELECTED_FILE_PATHS
    do
        FILE=${FPATH##*/}
        echo "Processing file:"$FILE >> $LOG
        
        /usr/bin/mv ${FILE} ${ORG_DIR}/${FILE}
        [[ $? -eq 0 ]] || fail "Failed moving file: ${FILE} to ${ORG_DIR}/${FILE}"

        /usr/bin/convert -rotate $ROTATE_ANGLE ${ORG_DIR}/${FILE} ${FILE}
        [[ $? -eq 0 ]] || fail "Failed converting file: ${FILE}"
    done
}

mkdir $ORG_DIR

rotateFiles ${ROTATE_ANGLE}
